
package bank;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankAccount", targetNamespace = "http://bank/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankAccount {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AccountExists")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AccountExists", targetNamespace = "http://bank/", className = "bank.AccountExists")
    @ResponseWrapper(localName = "AccountExistsResponse", targetNamespace = "http://bank/", className = "bank.AccountExistsResponse")
    public boolean accountExists(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AccountBalance")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AccountBalance", targetNamespace = "http://bank/", className = "bank.AccountBalance")
    @ResponseWrapper(localName = "AccountBalanceResponse", targetNamespace = "http://bank/", className = "bank.AccountBalanceResponse")
    public boolean accountBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ChangeBalance")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ChangeBalance", targetNamespace = "http://bank/", className = "bank.ChangeBalance")
    @ResponseWrapper(localName = "ChangeBalanceResponse", targetNamespace = "http://bank/", className = "bank.ChangeBalanceResponse")
    public boolean changeBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
