
package bank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankAccountService", targetNamespace = "http://bank/", wsdlLocation = "http://127.0.0.1:7001/hw4/BankAccountService?WSDL")
public class BankAccountService
    extends Service
{

    private final static URL BANKACCOUNTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKACCOUNTSERVICE_EXCEPTION;
    private final static QName BANKACCOUNTSERVICE_QNAME = new QName("http://bank/", "BankAccountService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7001/hw4/BankAccountService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKACCOUNTSERVICE_WSDL_LOCATION = url;
        BANKACCOUNTSERVICE_EXCEPTION = e;
    }

    public BankAccountService() {
        super(__getWsdlLocation(), BANKACCOUNTSERVICE_QNAME);
    }

    public BankAccountService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKACCOUNTSERVICE_QNAME, features);
    }

    public BankAccountService(URL wsdlLocation) {
        super(wsdlLocation, BANKACCOUNTSERVICE_QNAME);
    }

    public BankAccountService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKACCOUNTSERVICE_QNAME, features);
    }

    public BankAccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankAccountService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankAccount
     */
    @WebEndpoint(name = "BankAccountPort")
    public BankAccount getBankAccountPort() {
        return super.getPort(new QName("http://bank/", "BankAccountPort"), BankAccount.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankAccount
     */
    @WebEndpoint(name = "BankAccountPort")
    public BankAccount getBankAccountPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bank/", "BankAccountPort"), BankAccount.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKACCOUNTSERVICE_EXCEPTION!= null) {
            throw BANKACCOUNTSERVICE_EXCEPTION;
        }
        return BANKACCOUNTSERVICE_WSDL_LOCATION;
    }

}
